### PR TITLE
added unofficial

### PR DESCRIPTION
**Pull request by alestor123**
I have add unofficial to the title @RIAEvangelist

### CODE REVIEW

**Comment by RIAEvangelist** [comment]
I do not see a need to add this as there is no official api. Because there is not official API, there should also be no unofficial APIs. This has been running like this for 5 or 6 years, so I don't see the value in adding it now.

**Comment by Heath123** [comment]
Because people will think it is official

**Comment by RIAEvangelist** [comment]
Understood. There has been enough feedback on this to warrant consideration. I will update appropriately.

**Comment by RIAEvangelist** [comment]
There does not seem to be any issue with this at the moment. If that changes in the future we will re-open and consider again. Thank you for your submission though!

**Pull request closed without merging**
